name: Macker

on:
  push:
    branches:
      - main
  pull_request: {}

concurrency:
  group: macker-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    name: "Release build on ${{ matrix.os }}"
    strategy:
      matrix:
        os: [macos-13]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: jdx/mise-action@v2
        with:
          experimental: true
      - name: Run
        run: mise run build

  build_tuist:
    name: "Tuist build"
    runs-on: "macos-13"
    steps:
      - uses: actions/checkout@v3
      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_$(cat .xcode-version).app
      - uses: jdx/mise-action@v2
        with:
          experimental: true
      - name: Run
        run: |
          mise x -- tuist install
          mise run build:tuist

  test:
    name: "Test on ${{ matrix.os }}"
    strategy:
      matrix:
        os: [macos-13]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: jdx/mise-action@v2
        with:
          experimental: true
      - name: Run
        run: mise run test

  test_tuist:
    name: "Tuist test"
    runs-on: "macos-13"
    env:
      TUIST_CONFIG_CLOUD_TOKEN: ${{ secrets.TUIST_CONFIG_CLOUD_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_$(cat .xcode-version).app
      - uses: jdx/mise-action@v2
        with:
          experimental: true
      - name: Run
        run: |
          mise x -- tuist install
          mise run test:tuist

  lint:
    name: Lint
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - uses: jdx/mise-action@v2
        with:
          experimental: true
      - name: Run
        run: mise run lint